import{i as c,S as d}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();function u({views:r,downloads:t,likes:s,comments:a,webformatURL:e,largeImageURL:o,tags:i}){return`<li class="card">
      <a class="card-image-wrapper" href="${o}">
        <img class="card-image" src="${e}" alt="${i}" data-full="${o}">
      </a>
      <ul class="card-content">
        <li class="card-content-item">Likes <span data-likes="">${s}</span></li>
        <li class="card-content-item">Comments <span data-comments="">${a}</span></li>
        <li class="card-content-item">Views <span data-views="">${r}</span></li>
        <li class="card-content-item">Downloads <span data-downloads="">${t}</span></li>
      </ul>
    </li>`}function m(r){return r.map(t=>u(t)).join("")}const p="https://pixabay.com",f="/api/";function h(r){r=r.toLowerCase().split(" ").join("+").toString();const t=new URLSearchParams({key:"44424725-c6298a470a26677f9f5105ec2",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"}),s=`${p}${f}?${t}`;return fetch(s).then(a=>a.json()).catch(a=>console.log(a))}const n={form:document.querySelector(".entry-form"),input:document.querySelector(".entry-form-input"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")},y={titleColor:"#FFFFFF",messageColor:"#FFFFFF",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",message:"Sorry, there are no images matching<br>your search query.Please try again!",position:"topRight",iconUrl:"../img/error.svg"},g={captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.8};let l;function L(){n.loader.classList.remove("visually-hidden")}function F(){n.loader.classList.add("visually-hidden")}function w(r){n.gallery.innerHTML="",L(),h(r).then(t=>{if(t.hits.length===0){c.show(y);return}const s=m(t.hits);n.gallery.insertAdjacentHTML("afterbegin",s),l=new d(".gallery a",g),l.refresh(),l.on("show.simplelightbox")}).finally(()=>F())}n.form.addEventListener("submit",r=>{r.preventDefault();const t=n.input.value.trim();w(t),n.form.reset()});
//# sourceMappingURL=commonHelpers.js.map
